const client = load('@/database');
const fs = require('fs');

class MigrationsManager {
  #migrationsTableTitle = 'MIGRATIONS';
  
 async init() {
    await this.#createTable();

    await this.runMigrations();
  }

  #createTable() {
    const query = `
      CREATE TABLE IF NOT EXISTS ${this.#migrationsTableTitle}(
       ID BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
       TITLE TEXT NOT NULL
     )    
    `;
    return client.query(query);
  }

  async runMigrations() {
    const files = fs.readdirSync(resolve('@/migrations')).filter(fl => fl.endsWith('.sql'));
    const statuses = await Promise.all(files.map(fl => this.#isMigrationInstalled(fl.split('.')[0])));
    for (let i = 0; i < statuses.length; i++) {
      if (statuses[i]) continue;
      console.log('uninstalled migration', files[i]);
      await this.#installMigration(files[i]);
    }
  }

  revertMigrations() {

  }

  async #isMigrationInstalled(migrationTitle) {
    const query = `
      SELECT EXISTS(
        SELECT 
          ID
        FROM
          ${this.#migrationsTableTitle}
        WHERE
          TITLE = $1
      )
    `;
    const response = await client.query(query, [migrationTitle]);
    return response.rows[0].exists;
  }

  async #installMigration(file) {
    const query = fs.readFileSync(resolve(`@/migrations/${file}`), 'utf8');
    const res = await client.query(query);
    this.#updateInstallationStatus(file.split('.')[0]);
  }

  async #updateInstallationStatus(migrationTitle) {
    const query = `
      INSERT INTO
        ${this.#migrationsTableTitle} (
        TITLE
      ) VALUES (
        $1
      )
    `;
    await client.query(query, [migrationTitle]);
  }
}

const migrationsManager = new MigrationsManager();
migrationsManager.init();
