CREATE TABLE INVITATION_CODES (
  ID BIGINT NOT NULL PRIMARY KEY,
  VALUE TEXT NOT NULL
)

CREATE TABLE USERS (
  ID BIGINT NOT NULL PRIMARY KEY,
  USERNAME TEXT NOT NULL,
  EMAIL TEXT NOT NULL,
  PASSWORD TEXT NOT NULL,
  REGISTRATION_DATETIME DATETIME DEFAULT NOW(),
  VERIFIED BOOLEAN DEFAULT FALSE,
  VERIFICATION_TOKEN TEXT NOT NULL.
  INVITATION_CODE_ID BIGINT
  FOREIGN KEY(INVINTATION_CODE_ID) REFERENCES INVITATION_CODES(ID)
);

CREATE TABLE USERS_SESSIONS (
  ID BIGINT NOT NULL PRIMARY KEY,
  USER_ID BIGINT NOT NULL,
  USER_AGENT TEXT NOT NULL,
  IP_ADDRESS TINYTEXT NOT NULL,
  ACCESS_TOKEN TEXT DEFAULT NULL,
  ACCESS_TOKEN_GENERATION_DATETIME DATETIME DEFAULT NULL,
  FOREIGN KEY(USER_ID) REFERENCES USERS(ID)
);

